#!/bin/bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

INTERFACE="${BLOCK_INSTANCE:-wlan0}"

#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
    [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && exit

SSID=$(iwgetid $INTERFACE -r)
IP=$(ip -f inet addr show ${INTERFACE} | grep -Po 'inet \K[\d.]+' | head -n1)
SIGNAL=$(iw dev ${INTERFACE} link | grep signal | egrep -o '[0-9]+')

echo "${IP} (${SSID})"
echo "${IP} (${SSID})"

if [ "$SIGNAL" -lt 68 ]; then
    echo "#74aa04";
elif [ "$SIGNAL" -lt 70 ]; then
    echo "#b6b649";
else
    echo "#a70334";
fi
