.PHONY: prereq install

prereq:

install:
	@sudo pacman --noconfirm --needed -S xorg-xinit xorg-xclock artwiz-fonts unclutter gnome-themes-standard numix-themes lxappearance feh
	@yaourt --noconfirm --needed -S lemonbar-git compton-git paper-gtk-theme-git
