.PHONY: prereq install

prereq:

install:
	@sudo pacman --noconfirm --needed -S xorg-xinit xorg-xclock artwiz-fonts unclutter gnome-themes-standard numix-themes lxappearance
	@yaourt --noconfirm --needed -S lemonbar-git imlibsetroot compton-git paper-gtk-theme-git
