#! /bin/sh

bspc config border_width                1
bspc config window_gap                  15

bspc config top_padding                 16
bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true
bspc config auto_alternate              true
bspc config active_border_color         "#3F4B9C"
bspc config focused_border_color        "#3F4B9C"
bspc config presel_border_color         "#181818"
bspc config urgent_border_color         "#C90515"
bspc config focused_locked_border_color "#8c644c"

bspc config normal_frame_opacity        0.0
bspc config focused_frame_opacity       0.1

if [ -x $(dirname $0)/bspwmrc.local ]; then
  $(dirname $0)/bspwmrc.local
else
  bspc monitor -d one two three four five six
fi

$(dirname $0)/panel &
sxhkd &

