set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'valloric/YouCompleteMe'
Plugin 'altercation/vim-colors-solarized'
Plugin 'chriskempson/base16-vim'
call vundle#end()
filetype plugin indent on

syntax on

" color schemes

" Euphrasia
"colorscheme euphrasia

" Solarized Dark
"set background=dark
"colorscheme solarized

" Base16 Tomorrow
"set background=dark
"colorscheme base16-tomorrow

" Smyck
colorscheme smyck

" The following lines may have to be uncommented in order for the terminal to
" have a transparent background
hi Normal ctermbg=none
hi NonText ctermbg=none

python from powerline.vim import setup as powerline_setup
python powerline_setup()
python del powerline_setup

set laststatus=2
set clipboard=unnamed " yank to X clipboard
set pastetoggle=<F2>
set autoindent
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set showmatch
set incsearch
